// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721162930_AddSubjectChunkSettings")]
    partial class AddSubjectChunkSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.AIGenerationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeneratedQuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AIGenerationLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AddonPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("QuotaAmount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AddonPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Gói Mini (Cấp tốc)",
                            Price = 10000m,
                            QuotaAmount = 75000
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gói Standard (Cứu cánh)",
                            Price = 20000m,
                            QuotaAmount = 200000
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Gói Ultra (Chạy nước rút)",
                            Price = 50000m,
                            QuotaAmount = 600000
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            OrderIndex = 1,
                            SubjectId = 1,
                            Title = "Chapter 01 - Networking Programming"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            OrderIndex = 2,
                            SubjectId = 1,
                            Title = "Chapter 02 - Asynchronous and Parallel Programming in .NET"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            OrderIndex = 1,
                            SubjectId = 2,
                            Title = "Chương 1: Tổng quan AI"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            OrderIndex = 3,
                            SubjectId = 1,
                            Title = "Chapter 03 - Dependency Injection in .NET"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            OrderIndex = 4,
                            SubjectId = 1,
                            Title = "Chapter 04 - Building Web Application using ASP.NET Core MVC"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            OrderIndex = 5,
                            SubjectId = 1,
                            Title = "Chapter 05 - Building Websites Using ASP.NET Core Razor Pages"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            OrderIndex = 6,
                            SubjectId = 1,
                            Title = "Chapter 06 - Building a Web App with Blazor and ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            OrderIndex = 7,
                            SubjectId = 1,
                            Title = "Chapter 07 - Real-Time Communication"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            OrderIndex = 8,
                            SubjectId = 1,
                            Title = "Chapter 08 - Background Tasks with Worker Service"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            OrderIndex = 1,
                            SubjectId = 3,
                            Title = "Ch01 - Introduction"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            OrderIndex = 2,
                            SubjectId = 3,
                            Title = "Ch02 - Overview of UML Notation"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            OrderIndex = 3,
                            SubjectId = 3,
                            Title = "Ch03 - Software Life Cycle Models and Processes"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            OrderIndex = 4,
                            SubjectId = 3,
                            Title = "Ch04 - Software Design and Architecture Concepts"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            OrderIndex = 5,
                            SubjectId = 3,
                            Title = "Ch05 - Overview of Software Modeling and Design"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            OrderIndex = 6,
                            SubjectId = 3,
                            Title = "Ch06 - Use Case Modeling"
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            OrderIndex = 7,
                            SubjectId = 3,
                            Title = "Ch07 - Static Modeling"
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            OrderIndex = 8,
                            SubjectId = 3,
                            Title = "Ch08 - Object and Class Structuring"
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            OrderIndex = 9,
                            SubjectId = 3,
                            Title = "Ch09-11 - Dynamic Modeling"
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            OrderIndex = 10,
                            SubjectId = 3,
                            Title = "Ch12 - Overview of Software Architecture"
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            OrderIndex = 11,
                            SubjectId = 3,
                            Title = "Ch13 - Software Subsystem Architectural Design"
                        },
                        new
                        {
                            Id = 21,
                            IsDeleted = false,
                            OrderIndex = 12,
                            SubjectId = 3,
                            Title = "Ch14 - Designing Object-Oriented Software Architecture"
                        },
                        new
                        {
                            Id = 22,
                            IsDeleted = false,
                            OrderIndex = 13,
                            SubjectId = 3,
                            Title = "Ch15 - Designing Client Server Software Architecture"
                        },
                        new
                        {
                            Id = 23,
                            IsDeleted = false,
                            OrderIndex = 14,
                            SubjectId = 3,
                            Title = "Ch16 - Designing Service-Oriented Architecture"
                        },
                        new
                        {
                            Id = 24,
                            IsDeleted = false,
                            OrderIndex = 15,
                            SubjectId = 3,
                            Title = "Ch17 - Designing Component-Based Software Architecture"
                        },
                        new
                        {
                            Id = 25,
                            IsDeleted = false,
                            OrderIndex = 16,
                            SubjectId = 3,
                            Title = "Ch18 - Designing Concurrent and Real-Time Software Architecture"
                        },
                        new
                        {
                            Id = 26,
                            IsDeleted = false,
                            OrderIndex = 17,
                            SubjectId = 3,
                            Title = "Ch20 - Software Quality Attributes"
                        },
                        new
                        {
                            Id = 27,
                            IsDeleted = false,
                            OrderIndex = 18,
                            SubjectId = 3,
                            Title = "Ch21 - Client Server Software Architecture Case Study"
                        },
                        new
                        {
                            Id = 28,
                            IsDeleted = false,
                            OrderIndex = 19,
                            SubjectId = 3,
                            Title = "Ch22 - SOA Case Study - Online Shopping System"
                        },
                        new
                        {
                            Id = 29,
                            IsDeleted = false,
                            OrderIndex = 20,
                            SubjectId = 3,
                            Title = "Ch23 - Component-Based Software Architecture Case Study"
                        },
                        new
                        {
                            Id = 30,
                            IsDeleted = false,
                            OrderIndex = 21,
                            SubjectId = 3,
                            Title = "Ch24 - Real-Time Software Architecture Case Study"
                        },
                        new
                        {
                            Id = 31,
                            IsDeleted = false,
                            OrderIndex = 22,
                            SubjectId = 3,
                            Title = "SWD392 - Design Pattern"
                        },
                        new
                        {
                            Id = 32,
                            IsDeleted = false,
                            OrderIndex = 23,
                            SubjectId = 3,
                            Title = "SWD392 - GenAI"
                        },
                        new
                        {
                            Id = 33,
                            IsDeleted = false,
                            OrderIndex = 24,
                            SubjectId = 3,
                            Title = "SWD392 - RDS Document Case Study"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("CitationPayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UploaderId")
                        .HasColumnType("integer");

                    b.Property<string>("ViewUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentActivityLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualTransferContent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AddonId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("SenderAccountInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddonId");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsAIGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("QuestionBanks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Từ khóa nào được dùng để khai báo hằng số trong C#?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"readonly\",\"const\",\"static\",\"let\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "Syntax,Variables"
                        },
                        new
                        {
                            Id = 2,
                            Content = "C# là một ngôn ngữ lập trình thuần hướng đối tượng (Pure Object-Oriented). Đúng hay Sai?",
                            CorrectAnswer = "False",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            QuestionType = "TrueFalse",
                            SubjectId = 1,
                            Tags = "OOP,Theory"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Middleware nào được sử dụng để phục vụ các tệp tĩnh (static files) như HTML, CSS, JS trong ASP.NET Core?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"UseRouting()\",\"UseStaticFiles()\",\"UseEndpoints()\",\"UseHttpsRedirection()\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 2,
                            Tags = "Middleware,StaticFiles"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Nếu trình duyệt của client không hỗ trợ WebSockets, SignalR trong ASP.NET Core sẽ tự động fallback (lùi về) sử dụng các cơ chế nào?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Chỉ Long Polling\",\"Server-Sent Events và Long Polling\",\"gRPC và TCP\",\"Không có cơ chế fallback\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "SignalR,WebSockets"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Sự khác biệt cốt lõi giữa giao thức TCP và UDP là gì?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"TCP nhanh hơn UDP gấp nhiều lần\",\"TCP đảm bảo truyền tin cậy (không mất gói tin), UDP thì không\",\"UDP mặc định mã hóa dữ liệu, TCP thì không\",\"Cả hai đều không yêu cầu thiết lập kết nối (connectionless)\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "TCP,UDP,Protocols"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Mã trạng thái HTTP (Status Code) nào báo hiệu rằng người dùng chưa đăng nhập hoặc cung cấp Token không hợp lệ?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"400 Bad Request\",\"403 Forbidden\",\"401 Unauthorized\",\"404 Not Found\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "HTTP,StatusCode,Security"
                        },
                        new
                        {
                            Id = 7,
                            Content = "CORS (Cross-Origin Resource Sharing) trong ASP.NET Core API được sử dụng để giải quyết bài toán gì?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Bảo vệ CSDL khỏi SQL Injection\",\"Cho phép hoặc chặn các Request gọi từ các Domain/Port khác\",\"Mã hóa mật khẩu người dùng trước khi lưu\",\"Tối ưu hóa tốc độ tải trang (Caching)\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "CORS,Security,API"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Trong kiến trúc gRPC của .NET, định dạng nào được sử dụng để tuần tự hóa (serialize) dữ liệu truyền đi thay cho JSON?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"XML\",\"BSON\",\"Protocol Buffers (Protobuf)\",\"MessagePack\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "gRPC,Serialization"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Phương thức HTTP nào được thiết kế chuẩn để cập nhật MỘT PHẦN dữ liệu của tài nguyên thay vì cập nhật toàn bộ?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"PUT\",\"POST\",\"PATCH\",\"UPDATE\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "HTTP,REST"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Để ánh xạ (map) một SignalR Hub vào Endpoint Routing trong file Program.cs của .NET 8, ta dùng phương thức nào?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"app.MapControllers()\",\"app.AddSignalR()\",\"app.MapHub<THub>()\",\"app.UseWebSockets()\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "SignalR,Routing"
                        },
                        new
                        {
                            Id = 11,
                            Content = "YARP (Yet Another Reverse Proxy) của Microsoft thường được dùng trong trường hợp nào?",
                            CorrectAnswer = "A",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Làm API Gateway điều hướng request cho các Microservices\",\"Thay thế Entity Framework Core\",\"Quản lý background jobs như Hangfire\",\"Tạo giao diện người dùng thời gian thực\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "YARP,Microservices,Proxy"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Bản chất của kết nối WebSocket là gì?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Giao tiếp 1 chiều từ Client lên Server\",\"Kết nối 2 chiều (Bi-directional) toàn thời gian qua 1 TCP Socket\",\"Request-Response liên tục (Polling)\",\"Chỉ mở kết nối khi Server có dữ liệu mới\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "WebSockets,RealTime"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Khi cấu hình Middleware trong ASP.NET Core, thứ tự khai báo (chẳng hạn UseAuthentication trước UseAuthorization) có quan trọng không?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Không quan trọng, .NET sẽ tự động sắp xếp lại\",\"Chỉ quan trọng khi cấu hình CORS\",\"Có, thứ tự cực kỳ quan trọng vì Request đi qua theo thứ tự khai báo\",\"Không, tất cả middleware chạy song song cùng lúc\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "Middleware,ASP.NETCore"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Namespace nào trong .NET cung cấp các lớp (classes) làm việc trực tiếp ở tầng thấp với TCP/UDP như TcpListener, UdpClient?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Easy",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"System.Net.Http\",\"Microsoft.AspNetCore.Http\",\"System.Net.Sockets\",\"System.IO.Ports\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "Sockets,Networking"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Trong SignalR, làm thế nào để Hub Server gửi một tin nhắn trực tiếp đến MỘT người dùng cụ thể đã được xác thực (đăng nhập)?",
                            CorrectAnswer = "D",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Hard",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Clients.All.SendAsync()\",\"Clients.Others.SendAsync()\",\"Clients.Group(userId).SendAsync()\",\"Clients.User(userId).SendAsync()\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "SignalR,Targeting"
                        },
                        new
                        {
                            Id = 16,
                            Content = "Công nghệ SSE (được SignalR dùng làm fallback) là viết tắt của từ gì?",
                            CorrectAnswer = "A",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Server-Sent Events\",\"Socket Secure Engine\",\"SignalR Streaming Extension\",\"Synchronous Server Endpoint\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "SSE,RealTime"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Trong ASP.NET Core, JWT (JSON Web Token) được ứng dụng chủ yếu vào mục đích gì trong môi trường mạng phân tán?",
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Lưu trữ Session trực tiếp trên RAM của Server\",\"Mã hóa dữ liệu trong Database\",\"Xác thực không trạng thái (Stateless Authentication)\",\"Chống lại tấn công DDoS\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "JWT,Security,Stateless"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Thuộc tính 'Idempotent' (Lũy đẳng) trong thiết kế REST API có nghĩa là gì?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Hard",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"API phản hồi cực kỳ nhanh\",\"Gọi API 1 lần hay nhiều lần liên tiếp đều sinh ra cùng một trạng thái hệ thống\",\"API chỉ cho phép giao tiếp mã hóa SSL\",\"API bắt buộc phải dùng JSON\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "REST,API,Architecture"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Việc thiết lập các Limits trên Kestrel Web Server (như MaxRequestBodySize, MaxConcurrentConnections) mang lại lợi ích chính gì?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Medium",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Tránh lãng phí bộ nhớ lưu trữ CSDL\",\"Bảo vệ Server khỏi quá tải hoặc các cuộc tấn công gửi dữ liệu lớn\",\"Tự động Scale-out server lên Kubernetes\",\"Tăng tốc độ mã hóa HTTPS\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "Kestrel,Security,Performance"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Trong .NET, để triển khai Rate Limiting (Giới hạn số lượng request từ 1 Client) một cách native từ .NET 7/8, ta dùng tính năng nào?",
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Difficulty = "Hard",
                            IsAIGenerated = false,
                            IsDeleted = false,
                            LecturerId = 2,
                            OptionsJson = "[\"Thư viện bên thứ ba như AspNetCoreRateLimit\",\"Rate Limiting Middleware tích hợp sẵn trong Microsoft.AspNetCore.RateLimiting\",\"Dùng Hangfire để đếm request\",\"Dùng SignalR\"]",
                            QuestionType = "MultipleChoice",
                            SubjectId = 1,
                            Tags = "RateLimiting,Middleware,Security"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionBankActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OldContentJson")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionBankId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionSnippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankId");

                    b.HasIndex("UserId");

                    b.ToTable("QuestionBankActivityLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradingMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShuffled")
                        .HasColumnType("boolean");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("NumVariants")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreDisplayTiming")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("ShowScoreAfterSubmit")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizActivityLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionBankId")
                        .HasColumnType("integer");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionBankId");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizAttempts");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionBankId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<int>("VariantIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HandledByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("RelatedTransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("ReporterId")
                        .HasColumnType("integer");

                    b.Property<string>("ReporterRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HandledByAdminId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChunkMaxWords")
                        .HasColumnType("integer");

                    b.Property<int?>("ChunkOverlapWords")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PRN222",
                            IsDeleted = false,
                            LecturerId = 2,
                            Name = "C# Nâng cao"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AI101",
                            IsDeleted = false,
                            LecturerId = 2,
                            Name = "Nhập môn AI"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SWD392",
                            IsDeleted = false,
                            LecturerId = 2,
                            Name = "Software Architecture and Design"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyQuestionLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gói cơ bản miễn phí",
                            DurationDays = 30,
                            Features = "[\"Hỏi đáp AI cơ bản\", \"Độ trễ phản hồi bình thường\", \"Giới hạn 50.000 token / 5 giờ\"]",
                            IsActive = true,
                            MonthlyQuestionLimit = 5,
                            Name = "Basic",
                            Price = 0m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gói nâng cao nhiều tính năng",
                            DurationDays = 30,
                            Features = "[\"Ưu tiên xử lý câu hỏi\", \"Tốc độ phản hồi AI nhanh hơn\", \"Giới hạn 100.000 token / 5 giờ\", \"Hỗ trợ tài liệu đính kèm\"]",
                            IsActive = true,
                            MonthlyQuestionLimit = 20,
                            Name = "Pro",
                            Price = 25000m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gói cao cấp không giới hạn",
                            DurationDays = 30,
                            Features = "[\"Không giới hạn token\", \"AI phản hồi tức thì\", \"Mô hình AI cao cấp nhất\", \"Hỗ trợ ưu tiên 24/7\"]",
                            IsActive = true,
                            MonthlyQuestionLimit = -1,
                            Name = "Ultra",
                            Price = 100000m,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TokenUsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("TokenUsageLogs");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<long>("ExtraTokenQuota")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("MonthlyTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuotaResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetOtp")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("ResetOtpExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ShortTermResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ShortTermTokensUsed")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SubscriptionExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("UseExtraQuota")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtraTokenQuota = 0L,
                            IsDeleted = false,
                            MonthlyTokensUsed = 0L,
                            PasswordHash = "student123",
                            Role = "Student",
                            ShortTermTokensUsed = 0L,
                            SubscriptionPlan = "Basic",
                            UseExtraQuota = false,
                            Username = "student"
                        },
                        new
                        {
                            Id = 2,
                            ExtraTokenQuota = 0L,
                            IsDeleted = false,
                            MonthlyTokensUsed = 0L,
                            PasswordHash = "lecturer123",
                            Role = "Lecturer",
                            ShortTermTokensUsed = 0L,
                            SubscriptionPlan = "Basic",
                            UseExtraQuota = false,
                            Username = "lecturer"
                        },
                        new
                        {
                            Id = 3,
                            ExtraTokenQuota = 0L,
                            IsDeleted = false,
                            MonthlyTokensUsed = 0L,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            ShortTermTokensUsed = 0L,
                            SubscriptionPlan = "Basic",
                            UseExtraQuota = false,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.AIGenerationLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatMessage", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Document", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Chapter", "Chapter")
                        .WithMany("Documents")
                        .HasForeignKey("ChapterId");

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId");

                    b.HasOne("DataAccessLayer.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId");

                    b.Navigation("Chapter");

                    b.Navigation("Subject");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentActivityLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.DocumentChunk", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.AddonPackage", "AddonPackage")
                        .WithMany()
                        .HasForeignKey("AddonId");

                    b.HasOne("DataAccessLayer.Entities.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddonPackage");

                    b.Navigation("SubscriptionPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionBank", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuestionBankActivityLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.QuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId");

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Quiz", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizActivityLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizAnswer", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.QuizAttempt", "Attempt")
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.QuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("QuestionBank");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizAttempt", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.QuestionBank", "QuestionBank")
                        .WithMany()
                        .HasForeignKey("QuestionBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionBank");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Report", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "HandledByAdmin")
                        .WithMany()
                        .HasForeignKey("HandledByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByAdmin");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "Lecturer")
                        .WithMany("AssignedSubjects")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.TokenUsageLog", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Chapter", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Navigation("AssignedSubjects");

                    b.Navigation("ChatSessions");

                    b.Navigation("PaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
