// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyQuestionLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "GÃ³i miá»…n phÃ­ cÆ¡ báº£n",
                            IsActive = true,
                            MonthlyQuestionLimit = 5,
                            Name = "Free",
                            Price = 0m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "GÃ³i cÆ¡ báº£n 100 cÃ¢u há»i/thÃ¡ng",
                            IsActive = true,
                            MonthlyQuestionLimit = 100,
                            Name = "Basic",
                            Price = 50000m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "GÃ³i cao cáº¥p khÃ´ng giá»›i háº¡n",
                            IsActive = true,
                            MonthlyQuestionLimit = -1,
                            Name = "Premium",
                            Price = 150000m,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MonthlyQuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuotaResetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("SubscriptionExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionPlan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            MonthlyQuestionCount = 0,
                            PasswordHash = "student123",
                            Role = "Student",
                            SubscriptionPlan = "Free",
                            Username = "student"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            MonthlyQuestionCount = 0,
                            PasswordHash = "lecturer123",
                            Role = "Lecturer",
                            SubscriptionPlan = "Free",
                            Username = "lecturer"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            MonthlyQuestionCount = 0,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            SubscriptionPlan = "Free",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
